library(shiny)
library(sRa)
library(air)
library(tidyverse)

shinyUI(fluidPage(theme = "www/paper_modified.css",
                  
  titlePanel("Enrolment Explorer"),
  sidebarLayout(fluid = TRUE,
    sidebarPanel(
                 helpText("Choose a measure, institution, and variable to visualize using XMR style charts."),
                 selectInput("measure", "\n Measure", 
                             choices = c(
                               "Unique Headcount" = "Unique Student Static", 
                               "FLE", 
                               "Calculated Full-Time" = "Calculated Full-Time for Year",
                               "Calculated Part-Time" = "Calculated Part-Time for Year")),
                 selectInput("inst", "Institution", 
                             choices = c("Medicine Hat College" = "MH",
                                         "Alberta College of Art and Design" = "AA",
                                         "Ambrose University College" = "CA", 
                                         "Athabasca University" = "AU", 
                                         "Augustana Faculty of the U of A" = "CL", 
                                         "Bow Valley College" = "VC", 
                                         "Canadian Nazarene University College" = "CN", 
                                         "Canadian University College" = "CU", 
                                         "Concrodia University College of Alberta" = "CC", 
                                         "Grand Prairie Regional College" = "GP", 
                                         "Grant MacEwan College" = "GM", 
                                         "Grant MacEwan University" = "GU", 
                                         "Keyano College" = "KC", 
                                         "King's University College" = "KK", 
                                         "Lakeland College" = "LL", 
                                         "Lethbridge College" = "LC", 
 
                                         "Mount Royal University" = "MU", 
                                         "Mount Royal College" = "MR", 
                                         "Norquest College" = "VE", 
                                         "Northern Alberta Institute of Technology" = "NA", 
                                         "Northern lakes College" = "VS", 
                                         "Olds College" = "OC", 
                                         "Portage College" = "VB", 
                                         "Red Deer College" = "RD", 
                                         "Southern Alberta Institute of Technology" = "SA", 
                                         "St.Mary's University College" = "SM", 
                                         "Taylor University College and Seminary" = "NB", 
                                         
                                         "University of Alberta" = "UA", 
                                         "University of Calgary" = "OC", 
                                         "University of Lethbridge" = "UL")),
                 selectizeInput("var", "Variable", 
                             choices = c("-" = "Provider",
                                         sort(c("Gender", 
                              "Credential Type",
                              "Legal Status", 
                              "Aboriginal Indicator",
                              "Year Of Study", 
                              "Grade Completed Year",
                              "Registration Type",
                              "Provider Service Area",
                              "Service Area",
                              "Program Band",
                              "Program Name",
                              "Program Specialization",
                              "Program Length",
                              "Census Division",
                              "Registration Status",
                              "Age Group",
                              "Level Of Study", 
                              "Session", 
                              "Current Status", 
                              "Source Country",
                              "CIP Level 2",
                              #"CIP Level 4", 
                              #"CIP Level 6",
                              "Province", 
                              "Provider Location")))),
                 checkboxInput("offshores", "Remove offshores", value = T),
                 checkboxInput("cs", "Remove continuing studies", value = T),
                 submitButton("Update View", icon("refresh")),
                 helpText("Data saved does not contain XMR calculations."),
                 downloadButton('downloadData', 'Save Data', 
                                style ="color: #fff; background-color: #337ab7; border-color: #2e6da4"),
                 #downloadButton('downloadPlot', 'Download Plot'),
    width = 2),
  
    mainPanel(
       plotOutput("xmr", width = "auto")
    )
  )
))
